### ISSUE TITLE
IC8 = TP2?

### ISSUE THREAD

**Issue by KeLaiFu** [robgmsn/PureVCO#1]
I've built the module from the 3.1 boards and can see something on the scope for saw and square but nothing audible. 

Upon looking at the board for any faults I noticed What I thought was TP2 is marked IC8, to which there isn't an entry for on the BOM

Also, R7 requires a 87k resistor, which don't seem to exist, I put an 86.6k one in there.

**Comment by robgmsn** [comment]
Support is only available to supporters of GMSN! via the forum: https://forum.gmsn.co.uk/
You can support GMSN! by buying PCBs and Panels via the webstore: https://gmsn.co.uk
A forum account can be created at checkout.
